### ISSUE TITLE
Binding stops working on Openhab 3.0.0.M1

### ISSUE THREAD

**Issue by Z0l** [souliss/bindingopenhab2#18]
Hello,

just wanted to try out the 3.0.0.M1 build but got the following for the souliss binding:
```
2020-10-17 14:57:04.713 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.souliss-2.5.3-SNAPSHOT_202003231843.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.souliss [207]

  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.core

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
```

**Comment by lucacalcaterra** [comment]
@fazioa probably 3.x break things ? When i'll have time i'll try to recompile it

**Comment by Z0l** [comment]
I was researching this myself, seems the core components have been renamed
according to this post:
https://community.openhab.org/t/the-road-ahead-reintegrating-esh/64670

refactoring of its namespace from org.eclipse.smarthome to org.openhab.

I wanted to recompile but having some trouble setting up Eclipse.

Cheers,

Zoltan

**Comment by fazioa** [comment]
Yes. Binding for OH3 need some little modify.

Il dom 18 ott 2020, 11:00 Z0l <notifications@github.com> ha scritto:

**Comment by lucacalcaterra** [comment]
https://github.com/lucacalcaterra/bindingopenhab2/releases/download/3.0.0-m1-20201018/org.openhab.binding.souliss-3.0.0-SNAPSHOT.jar 
Here file compiled  for oh 3.0M1

**Comment by Z0l** [comment]
You absolutely rock, thank you, this works! I was able to turn a light on
and off but my rules that control the heating didn't work (not related to
the binding), so I'll spend some more time figuring out version 3 next week.

Cheers,

Zoltan

**Comment by llamich** [comment]
Hello good evening.
I've been using souliss for a few years now and I'm very satisfied with it, I'm on version 2.5, but due to some problems (hard + soft) I've decided to jump to OH3. I found this thread and tried to install the binding for OH3. I have openHAB version 3.1.0. When trying to install it, it gives me the following error:

2021-11-06 18:48:48.022 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.souliss [245]
  Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi-3.16.200.jar:?]
2021-11-06 18:48:52.601 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.souliss-3.0.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.souliss [245]
  Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]

I am a bit lost. My programming experience is very small, so I ask for your help ...
 Thank you very much in advance!

**Comment by lucacalcaterra** [comment]
Hi , this binding is no more usable.. download latest oh 3.2-snapshot and use the souliss binding bundled. Let me know and leave a feedback.

**Comment by llamich** [comment]
Hello,
Thank you very much for your help, I have installed the latest version that you told me and I already have the Souliss binding working.
I have done some first tests. I will explain my experience, I have Typicals of the following types: T11, T19, T22, T31, T41, T42, T51, T52, T53 and T56. 
Of all of them, the ones that I think work are: T11, T22, T51, T52, T53 and T56. The rest I just can't get them to work properly. 
The one that worries me the most is the T19, Openhab is not able to identify the state of the light, although it is capable of varying its intensity. The operation is not quite correct. In fact, this Typical, the T19, has only worked more or less well for me in the "org.openhab.binding.souliss_2.4.0.201812300050.jar" version of the OH2 Binding.
In fact, the same thing happened to me as here: [https://github.com/souliss/bindingopenhab2/issues/16]
If you want I can comment on more things about my user experience.
Thank you very much in advance and cordial greetings.
Luis

**Comment by lucacalcaterra** [comment]
@llamich , so all those typicals works ? On my home i use more or less yours.. so i cannot test others  for now. Regard t19 i'll investigate ..

**Comment by lucacalcaterra** [comment]
Ps t31 typical is working ? It should be..

**Comment by llamich** [comment]
> Ps t31 typical is working ? It should be..

The truth is that I have not tested it at all, I have not managed to integrate it with my air conditioning system, in fact I only use it to enter the target temperature to the system ...

**Comment by llamich** [comment]
Hello, I have finally discovered what I think is a malfunction of the T19.
I previously (in Version 2.5 - org.openhab.binding.souliss_2.4.0.201812300050.jar) had only one thing / item that was associated with the Dimmer channel. With it, I'could on / off and gave the desired intensity in the same Item, now I need both ON/OFF & Dimmer Items(that's not a problem).
What I think is not right is that it indicates that the Dimmer is for example at 0% and the light is really on at 100%. So I think there is a problem with the synchronization of the Dimmer value of the Openhab binding with Souliss.
Souliss does inform openhab of the on / off channel status, that part does work correctly. 
On the other hand, it does not report the intensity dimmer channel (%). Thus it can happen that a t19 light is on at 100% and the dimmer channel appears at 0% and on the contrary it is off and the dimmer appears at 100%. This does not happen normally in the Souliss app, when we turn on a t19 light, it goes from 0% to the level it had previously.
Openhab only presents a change in the Dimmer if we make a variation in it from the souliss app (although not always) or if we do it directly from openhab. For example, if we introduce a variation in the Dimmer channel (Openhab), the light goes to ON mode. But if we go OFF (channel ON/OFF), the dimmer channel stays with the same value in openhab, and does not go to 0.
If we turn on the light from the physical switch, the light will have the intensity that it had stored in souliss and when turning it off and on again (physical switch) it maintains that intensity.
I do not know if my explanation has helped something or is that I am doing something wrong ... 
Thank you very much in advance!
Luis

**Comment by lucacalcaterra** [comment]
Hi, this version of binding it's bot ok on oh 3. You should install oh 3.2m4 , it has souliss binding integrated

**Comment by llamich** [comment]
Hi, you are right. Upgrading to oh 3.2m4 works for me. Although I have had to make two Channel Links (ON / OFF + Dimmer) for the same item. So, in this way, I have the result that I expected. When the light goes out, the dimmer goes to 0% ...
Thank you very much and greetings!
